### ISSUE TITLE
Move tutorial index to try.zeek

### ISSUE THREAD

**Issue by rsmmr** [zeek/try-zeek#11]
The tutorial index currently [lives on the old web server](https://old.zeek.org/documentation/tutorials/index.html) any problem moving that right into try.zeek?

**Comment by JustinAzoff** [comment]
Yeah.. can probably just merge that text into the first 'hello world' example readme.. the one at https://github.com/zeek/try-zeek/blob/master/manager/static/examples/hello/readme.markdown

**Comment by JustinAzoff** [comment]
Done in dd1b30ffcfc9518b4c
