### ISSUE TITLE
Switch Docker repos from `zeekurity/zeek` to `zeek/zeek`

### ISSUE THREAD

**Issue by ckreibich** [zeek/try-zeek#46]
We're going to drop the latter in the not too distant future.

**Comment by ckreibich** [comment]
And by "latter" I mean "former". :-)

**Comment by JustinAzoff** [comment]
Sounds good.  just need to do some `docker tag`ing on the host to ensure that once it's switched over the old versions can still be found.

**Comment by awelzel** [comment]
That was done by Justin.
