### ISSUE TITLE
try-zeek Docker image 502 Bad Gateway

### ISSUE THREAD

**Issue by david-burkett** [zeek/try-zeek#6]
I’ve tried running the latest version of try-zeek on fresh installs/fully up-to-date versions of:

Ubuntu 16.04/18.04

Commands ran:

`docket build -t trybro .`
`docker run —rm -d -p 80:80 try bro`

However when I try to connect to the VM/curl the localhost I receive a 502 Bad Gateway Error.

**Comment by JustinAzoff** [comment]
Ah, you likely need a bro image, if you run this and restart the container does it work?

    docker pull broplatform/bro:2.6.1

I bet I never tested what happens if you have zero individual bro container images pulled... so you get the 500 error instead of a more helpful message.

**Comment by JustinAzoff** [comment]
Oh, you also need to run it differently, like

     docker  run --name trybro -v /brostuff:/brostuff -v /var/run/docker.sock:/var/run/docker.sock -v /srv/trybro_data:/var/lib/redis --rm=true -p 80:80 trybro

or

    docker  run --name trybro -v /brostuff:/brostuff -v /var/run/docker.sock:/var/run/docker.sock  --rm=true -p 80:80 trybro

if  you don't care if the data is  persistent.

the systemd unit file (https://github.com/zeek/try-zeek/blob/master/trybro.service) does this for you as well as handles pulling the bro image before starting.

**Comment by david-burkett** [comment]
All of that worked great! Thank you so much and have a great week.
